### ISSUE TITLE
Suggested Changes in Readme.md File

### ISSUE THREAD

**Issue by Sumanth077** [vopani/waveton#11]
Suggested changes in [Waveton ReadMe.md](https://github.com/vopani/waveton/blob/main/README.md) for better readability.

In Applications Section
1.) Remove the word "each" which is unnecessary.
2.) Modify the word "change" to "changes".

<img width="918" alt="Screenshot 2022-07-01 at 10 43 04 AM" src="https://user-images.githubusercontent.com/66694715/176831469-bd65096f-11ce-4a1d-a10b-e084fb60c611.png">

**Comment by vopani** [comment]
Fixed via https://github.com/vopani/waveton/commit/8d6542756742f291087ee25cced990a7fad645c3
