### ISSUE TITLE
README correction

### ISSUE THREAD

**Issue by chitransh89** [vopani/waveton#3]
README.md for ner_annotation has incorrect path for the app while doing change directory (cd) in the 3rd step "Create a Virtual Environment".  skeleton_apps does not contain ner_annotation directory in the main branch. It lies in data_apps

**Comment by vopani** [comment]
Fixed via https://github.com/vopani/waveton/commit/a936ac96813ad5432363ae637b3572b3667e24de

Thanks @chitransh89 !
